# Question 1: Version of NumPy

In [1]:
import numpy as np
np.__version__

'1.21.5'

# Question 2: Number of records in the dataset

In [2]:
import pandas as pd
df_cars = pd.read_csv('car_data.csv')

In [3]:
len(df_cars)

11914

# Question 3: The most popular car manufacturers

In [4]:
df_cars['Make'].value_counts()[:3].index.tolist()

['Chevrolet', 'Ford', 'Volkswagen']

# Question 4: Number of unique Audi car models

In [5]:
df_cars[df_cars['Make']=='Audi']['Model'].nunique()

34

# Question 5: Number of columns with missing values

In [6]:
(df_cars.isna().sum()>0).value_counts()

False    11
True      5
dtype: int64

# Question 6: Does the median value change after filling missing values?


In [7]:
df_cars['Engine Cylinders'].median()

6.0

In [8]:
df_cars['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [9]:
df_cars['Engine Cylinders'].fillna(4)

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [10]:
df_cars['Engine Cylinders'].median()

6.0

In [11]:
df_cars['Engine Cylinders'].describe()

count    11884.000000
mean         5.628829
std          1.780559
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

# Questions 7: Value of the first element of w

### Select all the "Lotus" cars from the dataset. Select only columns "Engine HP", "Engine Cylinders". Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).

In [12]:
df_lotus= df_cars[df_cars['Make']=='Lotus'][['Engine HP','Engine Cylinders']].drop_duplicates()
len(df_lotus)

9

In [13]:
df_lotus

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

### Get the underlying NumPy array. Let's call it X.

In [14]:
x = df_lotus.to_numpy()
x

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

### Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [23]:
tx = x.T

In [25]:
XTX = tx.dot(x)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

### Invert XTX.

In [28]:
ix = np.linalg.inv(XTX)
ix

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

### Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].

In [18]:
y=[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

### Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [29]:
z= ix.dot(x.T)

In [30]:
w = z.dot(y)

In [31]:
w

array([  4.59494481, -63.56432501])

### What's the value of the first element of w?

In [33]:
w[0].round(4)

4.5949